# Generated by Django 5.2.7 on 2025-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products", models.CharField(max_length=128)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
