# Generated by Django 5.2.7 on 2025-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
