# Generated by Django 5.2.7 on 2025-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("price", models.FloatField()),
                ("size", models.IntegerField()),
                ("ingredients", models.TextField()),
            ],
        ),
    ]
