# Generated by Django 5.2.7 on 2025-10-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
