# Generated by Django 5.2.7 on 2025-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0002_cake_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
