# Generated by Django 5.2.7 on 2025-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0003_cake_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="stock",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
