# Generated by Django 5.2.7 on 2025-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0004_alter_cake_created_at_alter_cake_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
