# Generated by Django 5.2.7 on 2025-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0005_alter_cake_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="size",
            field=models.IntegerField(),
        ),
    ]
