# Generated by Django 5.2.7 on 2025-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0006_alter_cake_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
