# Generated by Django 5.2.7 on 2025-10-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0007_cake_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="size",
            field=models.CharField(max_length=32),
        ),
    ]
