# Generated by Django 5.2.7 on 2025-10-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0008_alter_cake_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="size",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
